### ISSUE TITLE
landscaper 0.3.0 controller panic

### ISSUE THREAD

**Issue by Haegi** [gardener/landscaper#73]
**How to categorize this issue?**

 /area control-plane
/kind bug
/priority normal

**What happened**:
During the helm chart installation of the controller:
```
helm upgrade -i -n ls-system landscaper ./charts/landscaper
```
The pod ran into a CrashLoopBackOff with this error message:
```
E1214 13:57:38.059921       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 234 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18cda60, 0x280b3b0)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x18cda60, 0x280b3b0)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/gardener/landscaper/pkg/landscaper/controllers/installations.(*actuator).SetupRegistries(0xc000422e70, 0x1d100a0, 0xc000042018, 0x0, 0x0, 0x0, 0xc0006bf528, 0x13e3bc9)
        /go/src/github.com/gardener/landscaper/pkg/landscaper/controllers/installations/registry.go:34 +0xa19
github.com/gardener/landscaper/pkg/landscaper/controllers/installations.(*actuator).initPrerequisites(0xc000422e70, 0x1d100a0, 0xc000042018, 0xc00037a000, 0x1, 0x1acbccd, 0x8)
        /go/src/github.com/gardener/landscaper/pkg/landscaper/controllers/installations/actuator.go:182 +0x6f
github.com/gardener/landscaper/pkg/landscaper/controllers/installations.(*actuator).reconcile(0xc000422e70, 0x1d100a0, 0xc000042018, 0xc00037a000, 0x2876860, 0xc0004ba100)
        /go/src/github.com/gardener/landscaper/pkg/landscaper/controllers/installations/actuator.go:148 +0x85
github.com/gardener/landscaper/pkg/landscaper/controllers/installations.(*actuator).Reconcile(0xc000422e70, 0xc0004ba188, 0x7, 0xc0004ba184, 0x4, 0x28dc4700, 0x0, 0x0, 0x0)
        /go/src/github.com/gardener/landscaper/pkg/landscaper/controllers/installations/actuator.go:139 +0x92c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00051a600, 0x1936940, 0xc0005bc120, 0x0)
        /go/src/github.com/gardener/landscaper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00051a600, 0x203000)
        /go/src/github.com/gardener/landscaper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00051a600)
        /go/src/github.com/gardener/landscaper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000408190)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000408190, 0x1cd2c80, 0xc0005021e0, 0x1, 0xc000427aa0)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000408190, 0x3b9aca00, 0x0, 0x1, 0xc000427aa0)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000408190, 0x3b9aca00, 0xc000427aa0)
        /go/src/github.com/gardener/landscaper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/src/github.com/gardener/landscaper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x32d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1745079]
```

**What you expected to happen**:
The helm chart installation/upgrade works fine.

**How to reproduce it (as minimally and precisely as possible)**:
Contact us if you need more information.

**Anything else we need to know?**:

**Environment**:
k8s 1.18.12
GCP

- Landscaper version: 0.3.0
- Kubernetes version (use `kubectl version`): v1.19.4
- Others:

Tagging my pair @kramerul

**Comment by kramerul** [comment]
This morning I updated the helm chart

```
$ cd ~/workspace/landscaper
$ git status
HEAD detached at 0.3.0
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	landscaper-cli
nothing added to commit but untracked files present (use "git add" to track)
$ helm uninstall -n ls-system landscaper
$ helm install -n ls-system landscaper ~/workspace/landscaper/charts/landscaper -f values.yaml --create-namespace
$ helm list -A
NAME      	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
landscaper	ls-system	1       	2020-12-15 09:08:50.853947 +0100 CET	deployed	landscaper-0.1.0	0.1.0
$ kubectl -n ls-system get deploy landscaper -o yaml | grep image
                f:image: {}
                f:imagePullPolicy: {}
        image: eu.gcr.io/gardener-project/landscaper/landscaper-controller:0.1.0
        imagePullPolicy: IfNotPresent
```

It seems that the helm chart contained in your repo is not up to date.

**Comment by kramerul** [comment]
If we add 

```
image:
  tag: 0.3.0
```

to `values.yaml` the controller no longer panics.

**Comment by schrodit** [comment]
Ok guess we can then close the issue
